version: "3"
services:
  monitor:
    build: .
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8
    ports:
      - "8087:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=metrics

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
